version: '3'

services:
 poll_db:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: yes
   MYSQL_HOST: localhost
   MYSQL_PORT: 3306
  volumes:
   - "./initialize-db.sql:/docker-entrypoint-initdb.d/initialize-db.sql"
 poll-core:
  depends_on:
   - poll_db
  build : ../poll-core
  volumes:
   - ../poll-core:/usr/src/app
  ports:
   - 8080:8080