version: '3'

services:
 poll-web:
  depends_on:
   - poll-core
  build : ../social-poll-webapp/poll-webapp
  volumes:
   - ../poll-web:/usr/src/web
  ports:
   - 4200:4200
 poll_db:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes:
   - "./initialize-db.sql:/docker-entrypoint-initdb.d/initialize-db.sql"
 poll-core:
  depends_on:
   - poll_db
  build : ../poll-core
  volumes:
   - ../poll-core:/usr/src/app
  ports:
   - 8080:8080